module.exports = {
    CREATE_BUSINESS: 'CREATE-BUSINESS',
    UPDATE_BUSINESS: 'UPDATE-BUSINNESS',
    FIND_BUSINESS: 'FIND-BUSINESS',
    FIND_BUSINESS_BY_NAME: 'FIND-BUSINESS-BY-NAME',

    ADD_ROLE: 'ADD-ROLE',
    REMOVE_ROLE: 'REMOVE_ROLE',

    ADD_EMPLOYEE: 'ADD-EMPLOYEE',
    REMOVE_EMPLOYEE: 'REMOVE-EMPLOYEE',
    UPDATE_EMPLOYEE: 'UPDATE-EMPLOYEE',
    ADD_ROLE_TO_EMPLOYEE: 'ADD-ROLE-TO-EMPLOYEE',
    REVOKE_ROLE_TO_EMPLOYEE: 'REVOKE-ROLE-TO-EMPLOYEE', 

    ADD_CLIENT: 'ADD-CLIENT',
    DELETE_CLIENT: 'DELETE-CLIENT',
    UPDATE_CLIENT: 'UPDATE-CLIENT',
    

}